// local bill generation: calculate subtotal, tax, total
export default {
  generateBill: (req, res) => {
    try {
      const { items = [], tax_percent = 5, customer = null } = req.body || {};
      if (!Array.isArray(items) || items.length === 0) {
        return res.status(400).json({ error: 'items array required' });
      }
      const parsedItems = items.map(it => {
        const qty = Number(it.qty || 0);
        const unit_price = Number(it.unit_price || 0);
        const subtotal = +(qty * unit_price).toFixed(2);
        return { name: it.name, qty, unit_price, subtotal };
      });
      const subtotal = parsedItems.reduce((s, it) => s + it.subtotal, 0);
      const tax_amount = +(subtotal * (Number(tax_percent) / 100)).toFixed(2);
      const total = +(subtotal + tax_amount).toFixed(2);
      const bill = {
        customer,
        items: parsedItems,
        subtotal: +subtotal.toFixed(2),
        tax_percent: Number(tax_percent),
        tax_amount,
        total,
        note: 'Generated by Skill_Seva'
      };
      return res.json({ bill });
    } catch (err) {
      return res.status(500).json({ error: err?.message || 'server_error' });
    }
  }
};
